#!/usr/bin/python3
from sys import argv
def fined_print_devisor(a):
 for i in range(2,(a//2)+1):
   
   if a % i == 0:
     print("{:d}={:d}*{:d}".format(a,int(a/i),int(i)),end="")
     break
a = argv
f = open(a[1],"r")
for i in f.readlines():
  
  if i[-1] == '\n':
   num = int(i[:-1])
  else :
    num = int(i) 
  fined_print_devisor(num)
  
  print("")
